#!/bin/bash

# Generate the keystore
# The ${KEYPASS} is used to protect the private keys in the JKS keystore.
# It is also being used to convert the keystore generated by openssl from PKCS#12 to JKS format.
KEYPASS="jumpy-crazy-experience"
KEY_FILE="/home/turbonomic/data/keys/keystore.p12"
if [[ ! -f "${KEY_FILE}" ]]; then
  keytool -genkey -alias vmt -storetype PKCS12 -sigalg SHA256withRSA -keyalg RSA \
  -keysize 2048 -keystore ${KEY_FILE} -validity 3650 -storepass ${KEYPASS} \
  -keypass ${KEYPASS} -noprompt -dname "CN=turbonomic.com,OU=RND,O=TRB,L=NYC,S=NY,C=US" -ext san=ip:127.0.0.1 -ext san=dns:localhost
fi

# this is a new entrypoint.sh
# The Djava.security.egd=file:/dev/./urandom configuration significantly speeds up start-up time
# for the components using the SecureRandom class (see
# http://stackoverflow.com/questions/25660899/spring-boot-actuator-application-wont-start-on-ubuntu-vps)
COMMON_JAVA_OPTS="-XX:+UseG1GC -XX:CompileThreshold=1500 -XX:+ExitOnOutOfMemoryError"
COMMON_JAVA_OPTS="-verbose:gc -XX:+PrintGCDateStamps $COMMON_JAVA_OPTS"
COMMON_JAVA_OPTS="-XX:SoftRefLRUPolicyMSPerMB=0 -XX:+PrintConcurrentLocks -XX:+PrintClassHistogram $COMMON_JAVA_OPTS"
COMMON_JAVA_OPTS="-XX:+PrintCommandLineFlags -XX:+UseStringDeduplication -XX:StringDeduplicationAgeThreshold=1 $COMMON_JAVA_OPTS"
COMMON_JAVA_OPTS="-Djava.security.egd=file:/dev/./urandom -Djava.net.preferIPv4Stack=true -XX:-OmitStackTraceInFastThrow $COMMON_JAVA_OPTS"
COMMON_JAVA_OPTS="-Dnetworkaddress.cache.ttl=0 -Dnetworkaddress.cache.negative.ttl=0 $COMMON_JAVA_OPTS"
COMMON_JAVA_OPTS="-DLog4jContextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector $COMMON_JAVA_OPTS"

# Locate the jar
# We do that because we need an ability to handle version change.
# We assume we always have a single jar in /.
JAR=""
while read -r line
do
    JAR="${line}"
    break
done < <(ls -rt1 / | egrep ".*jar$")

export STARTUP_COMMAND="java $COMMON_JAVA_OPTS $JAVA_OPTS -jar ${JAR}"
exec $STARTUP_COMMAND 2>&1
